### PR TITLE
fix(core): assure that pseudo-classes warn when no arguments are given

### LINKED ISSUE #1936: Pseudo-class that expects a param should warn when none is given
```css
.root {
  -st-states: myState(string);
}

.root:myState {} /* should warn about missing argument */
```

### PR DESCRIPTION
**Pull request by tzachbon**
should warn when pseudo-class expects params but none was given

Closes #1936

### CODE REVIEW

File: packages/core/src/pseudo-states.ts [hunk 1]
```diff
@@ -295,6 +295,14 @@ function resolveStateValue(
         node.content || stateDef.defaultValue
     );
 
+    if (!actualParam && rule) {
+        diagnostics.warn(
+            rule,
+            `pseudo-state "${name}" expects a parameter of type ${stateDef.type} but none was given`,
```
Comment (idoros) [inline packages/core/src/pseudo-states.ts:301]: Add the warning (maybe error?) using the "state Errors" also use the same error function in the tests

File: packages/core/test/pseudo-states.spec.ts [hunk 2]
```diff
@@ -626,6 +626,58 @@ describe('pseudo-states', () => {
...
+                            .my-class {
+                                -st-states: state1;
+                            }
+                            .my-class:state1 {}
+                            `,
+                        },
+                    },
+                }
+
+                const res = expectWarningsFromTransform(config, [])
```
Comment (idoros) [inline packages/core/test/pseudo-states.spec.ts:674]: I would expect from the title of the test that the test would try to call the state, that was defined with no param, with a param

Comment (tomrav) [reply packages/core/test/pseudo-states.spec.ts:674]: Also I would say that generally we try not to test things that should "not happen"

Comment (tzachbon) [reply packages/core/test/pseudo-states.spec.ts:674]: I agree with that, but how would you make sure it won't happen? @tomrav @idoros

File: packages/core/src/pseudo-states.ts (hunk 1 above)
Comment (tzachbon) [reply packages/core/src/pseudo-states.ts:301]: Not sure I fully understand. Make it an error sounds legit tho.

File: packages/core/test/pseudo-states.spec.ts (hunk 2 above)
Comment (tomrav) [reply packages/core/test/pseudo-states.spec.ts:674]: In this case I probably wouldn't, and add a regression test only if it pops up somewhere unexpected somewhere down the line

Comment (idoros) [reply packages/core/test/pseudo-states.spec.ts:674]: I believe there are plenty of non param tests that check for diagnostics that would break if this new one would be reported for them.

Also, slightly related, I think it would be good to have a test that non param states that are called with a param also report an error (if non exist already)

Comment (tzachbon) [reply packages/core/test/pseudo-states.spec.ts]: I moved it to be a regression test.

**Review by barak007 — COMMENTED** [review]
Let's go over this together to see the thinking process.

File: packages/core/test/pseudo-states.spec.ts [hunk 3]
```diff
@@ -626,6 +649,35 @@ describe('pseudo-states', () => {
...
+                const config = {
+                    entry: `/entry.st.css`,
+                    files: {
+                        '/entry.st.css': {
+                            namespace: 'entry',
+                            content: `
+                            .my-class {
+                                -st-states: state1(string);
+                            }
+                            |.my-class:state1 {}
```
Comment (idoros) [inline packages/core/test/pseudo-states.spec.ts:662]: do you need the `|` (pipe) in this test?

File: packages/core/test/pseudo-states.spec.ts [hunk 4]
```diff
@@ -626,6 +649,35 @@ describe('pseudo-states', () => {
...
+                            `,
+                        },
+                    },
+                }
+
+                const res = expectWarningsFromTransform(config, [
+                    {
+                        message: 'pseudo-state "state1" defined with unknown type: "string"',
```
Comment (idoros) [inline packages/core/test/pseudo-states.spec.ts:670]: use the same `stateErrors,.*` to create the expected diagnostic message

Comment (tzachbon) [reply packages/core/test/pseudo-states.spec.ts]: Used new one.

File: packages/core/test/pseudo-states.spec.ts (hunk 3 above)
Comment (tzachbon) [reply packages/core/test/pseudo-states.spec.ts:662]: Yep, checking where the diagnostic accord.

File: packages/core/test/pseudo-states.spec.ts [hunk 5]
```diff
@@ -626,6 +649,64 @@ describe('pseudo-states', () => {
                 });
             });
 
+            it('should warn when pseudo-class expects params but none was given', () => {
```
Comment (barak007) [inline packages/core/test/pseudo-states.spec.ts:652]: all these test are also related to the fact that there is no default value. Add this into the test title

**Review by barak007 — CHANGES_REQUESTED** [review]
One last thing left.

File: packages/core/test/pseudo-states.spec.ts (hunk 4 above)
Comment (barak007) [reply packages/core/test/pseudo-states.spec.ts]: What Ido is saying here is use `stateErrors.UNKNOWN_STATE_TYPE` and don't repeat the error this way when the error is changed you don't need to change the test

File: packages/core/test/pseudo-states.spec.ts (hunk 5 above)
Comment (tzachbon) [reply packages/core/test/pseudo-states.spec.ts:652]: @barak007 done

File: packages/core/src/pseudo-states.ts [hunk 6]
```diff
@@ -295,6 +297,14 @@ function resolveStateValue(
         node.content || stateDef.defaultValue
     );
 
+    if (rule && !node.content && !stateDef.defaultValue) {
+        diagnostics.warn(
+            rule,
+            stateErrors.NO_STATE_ARGUMENT_GIVEN(name, stateDef.type),
+            { word: actualParam }
```
Comment (tomrav) [inline packages/core/src/pseudo-states.ts:304]: should probably target an existing string

File: packages/core/test/pseudo-states.spec.ts [hunk 7]
```diff
@@ -626,6 +649,64 @@ describe('pseudo-states', () => {
...
+                const config = {
+                    entry: `/entry.st.css`,
+                    files: {
+                        '/entry.st.css': {
+                            namespace: 'entry',
+                            content: `
+                            .my-class {
+                                -st-states: state1(string);
+                            }
+                            |.my-class:state1() {}
```
Comment (tomrav) [inline packages/core/test/pseudo-states.spec.ts:691]: fix piping and word selection

Comment (tomrav) [reply packages/core/test/pseudo-states.spec.ts:691]: consider moving diagnostics tests to bottom of file

**Review by tomrav — COMMENTED** [review]
Overall looks good! :+1:

**Review by tomrav — APPROVED** [review]
