### PR TITLE
fix: property definition override conflicting imported symbol

### LINKED ISSUE #1955: @property definition override conflicting imported symbol
### Actual Behavior

[Playground Link](wixplosives.github.io/stylable-playground/#state=%28%27files%21%282%21%27%2540st-import%2520%255B7%255D%2520from%2520%255C%27.3%255C%275*%2540property%252075*6*%2520%2520%2520%25204red5%29%27%7E3%21%2764green8.label18.icon18%27%29%7Eselected%212%278%255Cn0.st.css1%2520%282%27%252Findex03%252Fbutton047%253A%25205%253B*6.root17--x8%29*%2501876543210*_)

### Expected Behavior

We should not allow to redeclare imported css vars 

### Version

@stylable/core@4.5.0

### Relevant log output

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tzachbon**
Closes #1955

### CODE REVIEW

**Comment by tomrav** [comment]
We should probably also document the `@property` behavior on our site under the CSS var entry.

**Review by barak007 — APPROVED** [review]
Nice reuse

File: packages/core/src/stylable-processor.ts [hunk 1]
```diff
@@ -300,6 +300,7 @@ export class StylableProcessor {
 
                     break;
                 case 'property':
+                    this.checkRedeclareSymbol(atRule.params, atRule);
```
Comment (idoros) [inline packages/core/src/stylable-processor.ts:303]: this is checked only for `@property` because although setting and using css var is considered a declaration, it doesn't redeclare a variable if it exist in the scope?

Comment (barak007) [reply packages/core/src/stylable-processor.ts:303]: right

Comment (barak007) [reply packages/core/src/stylable-processor.ts:303]: it's only for the @property

File: packages/core/test/stylable-transformer/at-property.spec.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
+import { processorWarnings } from '@stylable/core';
+import { expectWarningsFromTransform, generateStylableResult } from '@stylable/core-test-kit';
 import { expect } from 'chai';
 import type * as postcss from 'postcss';
-import { generateStylableResult } from '@stylable/core-test-kit';
 
 describe('@property support', () => {
```
Comment (tomrav) [inline packages/core/test/stylable-transformer/at-property.spec.ts:6]: I think all these tests should move to the `css-vars.spec` file, not sure about this as a separate scope.

**Review by tomrav — APPROVED** [review]
Looks good :+1:

File: packages/core/test/stylable-transformer/at-property.spec.ts (hunk 2 above)
Comment (tzachbon) [reply packages/core/test/stylable-transformer/at-property.spec.ts:6]: Let's discuss it in a separate issue.
