### PR TITLE
fix: Stylable variables exports type and generated `dts` and `sourcemaps` files

### LINKED ISSUE #2249: Incorrect `stVars` type in Stylable exports
### Actual Behavior

`stVars` type is currently defined incorrectly as `Record<string, string>` and in fact, it could be nested with `st-map` and `st-array`.

(Both in `@stylable/core` and `@stylable/runtime`)

### Expected Behavior

Should support arrays and maps.

### Version

4.10.0 (latest)

### Relevant log output

[Example for complex case](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%2851%253A39*b8array%257Bred%2520%252Cblue%252C3d6%257D%257DC*cBoldC%257D0%29%27%7E%252Fbutton2%21%27.root4.label4.icon4%27%7E%252Fproject1ctive%253A6%253B9danger%253A%2520red%253B0%29%27%29%7Eselected%2152%27%29*770%255Cn12%21%21varsA9a2.st.css38map%257B4A%2905%27%252Findex6Breen7%2520%25208%2520st-90*A%2520%28B%2520gC%252C9%2501CBA9876543210*_)

### Additional Context

_No response_

### LINKED ISSUE #2250: Stylable CLI generates incorrect `dts` for complex `stVars`
### Actual Behavior

When generating `dts` for a stylesheet the `stVars` values will always be strings also if the object is more complex and have many levels.

### Expected Behavior

Will be the correct type according to the `stVars` definition.

### Version

4.10.0 (latest)

### Relevant log output

_No response_

### Additional Context

[Example for complex case (only the `stVar` definition)](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%2851%253A39*b8array%257Bred%2520%252Cblue%252C3d6%257D%257DC*cBoldC%257D0%29%27%7E%252Fbutton2%21%27.root4.label4.icon4%27%7E%252Fproject1ctive%253A6%253B9danger%253A%2520red%253B0%29%27%29%7Eselected%2152%27%29*770%255Cn12%21%21varsA9a2.st.css38map%257B4A%2905%27%252Findex6Breen7%2520%25208%2520st-90*A%2520%28B%2520gC%252C9%2501CBA9876543210*_)

### Blockers
[Fix the Stylable Exports types](https://github.com/wix/stylable/issues/2249)

### PR DESCRIPTION
**Pull request by tzachbon**
Closes #2249, closes #2250

Currently, there will be types duplication in the `core` and in the `runtime` packages.
There should be a decision if core should be dependent on the runtime or vise-versa, or there should be a dedicated `runtime-types` package. (#2257)

### CODE REVIEW

File: packages/module-utils/src/dts-rough-tokenizer.ts [hunk 1]
```diff
@@ -221,34 +226,60 @@ function findDtsTokens(tokens: DTSCodeToken[]) {
...
+                }
+                if (t.type === 'string') {
+                    const token: DtsToken = {
                         ...t,
                         line: lastNewLinePosition.line,
                         column: t.start - lastNewLinePosition.columm,
-                        outputValue: {
+                    };
+
+                    const value = s.peek(2);
```
Comment (tomrav) [inline packages/module-utils/src/dts-rough-tokenizer.ts:272]: add comment why peeking 2

File: packages/module-utils/src/generate-dts.ts [hunk 2]
```diff
@@ -63,10 +63,42 @@ function stringifyStates(meta: StylableMeta) {
     return out;
 }
 
-function stringifyStringRecord(record: Record<string, string>, indent = SPACING) {
-    return Object.keys(record)
-        .map((k) => `${indent}${asString(k)}: string;`)
-        .join('\n');
+function stringifyStringRecord(
+    record: Record<string, any>,
+    addParentasis = false,
```
Comment (tomrav) [inline packages/module-utils/src/generate-dts.ts:68]: `addParentheses`

File: packages/module-utils/src/generate-dts-sourcemaps.ts [hunk 3]
```diff
@@ -280,3 +322,20 @@ export function generateDTSSourceMap(dtsContent: string, meta: StylableMeta) {
         4
     );
 }
+
+function calculateEstimatedPosition(
```
Comment (tomrav) [inline packages/module-utils/src/generate-dts-sourcemaps.ts:326]: maybe open an issue (or comment on the value parser issue) about this as a tech debt

**Review by tomrav — APPROVED** [review]
looks good, left a couple of remarks

**Comment by AviVahl** [comment]
The new types that are part of the public api should be exported as well
